// <auto-generated />
using System;
using AutoStonks.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoStonks.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210201191203_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AutoStonks.API.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CarProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Displacement")
                        .HasColumnType("int");

                    b.Property<int>("DriveType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<bool>("HasBeenCrashed")
                        .HasColumnType("bit");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("AutoStonks.API.Models.AdvertEquipment", b =>
                {
                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("AdvertId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("AdvertEquipment");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Polonez"
                        });
                });

            modelBuilder.Entity("AutoStonks.API.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ABS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Centralny zamek"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elektryczne szyby przednia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Elektrycznie ustawiane lusterka"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Immobilizer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Poduszka powietrzna kierowcy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Poduszka powietrzna pasażera"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Radio fabryczne"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Wspomaganie kierownicy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Alarm"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Alufelgi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ASR (kontrola trakcji)"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Asystent parkowania"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Asysten pasa ruchu"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bluetooth"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Czujnik deszczu"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Czujnik martwego pola"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Czujnik zmierzchu"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Czujniki prakowania przednie"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Czujniki parkowania tylne"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Dach panoramiczny"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Elektrochromatyczne lusterka boczne"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Elektrochromatyczne lusterko wsteczne"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Elektryczne szyby tylne"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Elektrycznie ustawiane fotele"
                        },
                        new
                        {
                            Id = 27,
                            Name = "ESP (stabilizacja toru jazdy)"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Gniazdo AUX"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Gniazdo SD"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Gniazdo USB"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hak"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Isofix"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Kamera cofania"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Klimatyzacja automatyczna"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Klimatyzacja czterostrefowa"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Klimtayzacja dwustrefowa"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Klimatyzacja manualna"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Komputer pokładowy"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Kurtyny powietrzne"
                        },
                        new
                        {
                            Id = 40,
                            Name = "MP3"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Nawigacja GPS"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ogranicznik prędkości"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ogrzewanie postojowe"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Podgrzewana przednia szyba"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Podgrzewane lusterka boczne"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Podgrzewane przednie siedzenia"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Podgrzewane tylne siedzenia"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Szyberdach"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Światła do jazdy dziennej"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Światła LED"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Światła przecwmgielne"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Światła Xenonowe"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Tapicerka skórzana"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Tapicerka welurowa"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Tempomat"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Wielofunkcyjna kierownica"
                        });
                });

            modelBuilder.Entity("AutoStonks.API.Models.Generation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Generations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelId = 1,
                            Name = "III (2005-2012)"
                        },
                        new
                        {
                            Id = 2,
                            ModelId = 1,
                            Name = "IV (2012-2018)"
                        },
                        new
                        {
                            Id = 3,
                            ModelId = 1,
                            Name = "V (2019-)"
                        },
                        new
                        {
                            Id = 4,
                            ModelId = 2,
                            Name = "III (2008-2016)"
                        },
                        new
                        {
                            Id = 5,
                            ModelId = 2,
                            Name = "IV (2016-)"
                        },
                        new
                        {
                            Id = 6,
                            ModelId = 3,
                            Name = "III (2007-2015)"
                        },
                        new
                        {
                            Id = 7,
                            ModelId = 4,
                            Name = "III (2009-2013)"
                        },
                        new
                        {
                            Id = 8,
                            ModelId = 4,
                            Name = "I (2013-2019)"
                        },
                        new
                        {
                            Id = 9,
                            ModelId = 5,
                            Name = "E36 (1990-1999)"
                        },
                        new
                        {
                            Id = 10,
                            ModelId = 5,
                            Name = "E46 (1998-2007)"
                        },
                        new
                        {
                            Id = 11,
                            ModelId = 6,
                            Name = "E39 (1996-2003)"
                        },
                        new
                        {
                            Id = 12,
                            ModelId = 8,
                            Name = "E38 (1994-2001)"
                        },
                        new
                        {
                            Id = 13,
                            ModelId = 9,
                            Name = "W203 (2000-2007)"
                        },
                        new
                        {
                            Id = 14,
                            ModelId = 10,
                            Name = "W124 (1993-1997)"
                        },
                        new
                        {
                            Id = 15,
                            ModelId = 11,
                            Name = "B6 (2000-2004)"
                        },
                        new
                        {
                            Id = 16,
                            ModelId = 11,
                            Name = "B7 (2004-2007)"
                        },
                        new
                        {
                            Id = 17,
                            ModelId = 12,
                            Name = "C6 (2004-2011)"
                        },
                        new
                        {
                            Id = 18,
                            ModelId = 13,
                            Name = "D3 (2002-2010)"
                        },
                        new
                        {
                            Id = 19,
                            ModelId = 14,
                            Name = "I (2005-2012)"
                        },
                        new
                        {
                            Id = 20,
                            ModelId = 15,
                            Name = "I (2000-2010)"
                        },
                        new
                        {
                            Id = 21,
                            ModelId = 16,
                            Name = "I (1999-2006)"
                        },
                        new
                        {
                            Id = 22,
                            ModelId = 17,
                            Name = "I (2005-2010)"
                        },
                        new
                        {
                            Id = 23,
                            ModelId = 18,
                            Name = "C (2000-2006)"
                        },
                        new
                        {
                            Id = 24,
                            ModelId = 18,
                            Name = "D (2006-2014)"
                        },
                        new
                        {
                            Id = 25,
                            ModelId = 19,
                            Name = "C (2002-2008)"
                        },
                        new
                        {
                            Id = 26,
                            ModelId = 20,
                            Name = "A (2008-2017)"
                        },
                        new
                        {
                            Id = 27,
                            ModelId = 21,
                            Name = "B5 (1996-2000)"
                        },
                        new
                        {
                            Id = 28,
                            ModelId = 21,
                            Name = "B5 FL (2000-2005)"
                        },
                        new
                        {
                            Id = 29,
                            ModelId = 22,
                            Name = "V (2003-2009)"
                        },
                        new
                        {
                            Id = 30,
                            ModelId = 23,
                            Name = "V (2003-2009)"
                        },
                        new
                        {
                            Id = 31,
                            ModelId = 24,
                            Name = "Jetta IV (1998-2005)"
                        },
                        new
                        {
                            Id = 32,
                            ModelId = 25,
                            Name = "Mk7 (1995-1999)"
                        },
                        new
                        {
                            Id = 33,
                            ModelId = 26,
                            Name = "Mk2 (1987-1993)"
                        },
                        new
                        {
                            Id = 34,
                            ModelId = 27,
                            Name = "Mk4 (2018-)"
                        },
                        new
                        {
                            Id = 35,
                            ModelId = 28,
                            Name = "I (1978-1991)"
                        });
                });

            modelBuilder.Entity("AutoStonks.API.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Clio"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Megane"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "Laguna"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Name = "Scenic"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Name = "Captur"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "Seria 3"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Name = "Seria 5"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Name = "Seria 7"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Name = "Klasa C"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Name = "Klasa E"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 4,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            Name = "A8"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 5,
                            Name = "159"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            Name = "147"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 5,
                            Name = "156"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 5,
                            Name = "Brera"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 6,
                            Name = "Corsa"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 6,
                            Name = "Vectra"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 6,
                            Name = "Insignia"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 7,
                            Name = "Passat"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 7,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 7,
                            Name = "Bora"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 8,
                            Name = "Yaris"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 9,
                            Name = "Escort"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 9,
                            Name = "Sierra"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 9,
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 10,
                            Name = "Caro"
                        });
                });

            modelBuilder.Entity("AutoStonks.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentInitiation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentTermination")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("AutoStonks.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnforcePasswordChange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "napewnoniehandlarz@gmail.com",
                            EnforcePasswordChange = false,
                            IsActive = true,
                            LastPasswordChange = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "츊း뤮䷔뛦熜뀹獳㴗༫暸쨥櫆됈",
                            Role = "A",
                            Salt = "⣶刌䅦윽璅ꚮ�闏ⵁ堣帠䳀�壨瘶晤",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AutoStonks.API.Models.Advert", b =>
                {
                    b.HasOne("AutoStonks.API.Models.Generation", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoStonks.API.Models.User", "User")
                        .WithMany("Adverts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoStonks.API.Models.AdvertEquipment", b =>
                {
                    b.HasOne("AutoStonks.API.Models.Advert", "Advert")
                        .WithMany("AdvertEquipments")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoStonks.API.Models.Equipment", "Equipment")
                        .WithMany("AdvertEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Generation", b =>
                {
                    b.HasOne("AutoStonks.API.Models.Model", "Model")
                        .WithMany("Generations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Model", b =>
                {
                    b.HasOne("AutoStonks.API.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Payment", b =>
                {
                    b.HasOne("AutoStonks.API.Models.Advert", "Advert")
                        .WithMany("Payments")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Photo", b =>
                {
                    b.HasOne("AutoStonks.API.Models.Advert", "Advert")
                        .WithMany("Photos")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Advert", b =>
                {
                    b.Navigation("AdvertEquipments");

                    b.Navigation("Payments");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Equipment", b =>
                {
                    b.Navigation("AdvertEquipments");
                });

            modelBuilder.Entity("AutoStonks.API.Models.Model", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("AutoStonks.API.Models.User", b =>
                {
                    b.Navigation("Adverts");
                });
#pragma warning restore 612, 618
        }
    }
}
